# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e8860350984a2ec97e662c9eda6f9ef4121aa50dc17caa1e289d74031f06edb1cbf6be39af7a7ee9981fe19b02544724706d01c232f45f6fca703a7c5c7eb26

test:
  secret_key_base: 90d001383efc4e2f6aa24b681192147663fbb8b1e530fc88c30ac66bfcb3a5dcd2506ef500812033f7c4ef8e4f861754c31ec874aeb1e0c73aeaf000632961c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
